# Generated by Django 4.2 on 2024-09-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('transport', 'Transport'), ('flight', 'Flight'), ('accommodation', 'Accommodation'), ('sightseeing', 'Sightseeing'), ('outdoor_adventure', 'Outdoor Adventure'), ('water_activity', 'Water Activity'), ('cultural_experience', 'Cultural Experience'), ('leisure', 'Leisure'), ('sports_recreation', 'Sports & Recreation'), ('nightlife', 'Nightlife'), ('workshop', 'Workshop & Learning'), ('wildlife_experience', 'Wildlife Experience'), ('adventure_sports', 'Adventure Sports')], default='sightseeing', max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(choices=[('Argentina', 'Argentina'), ('Brazil', 'Brazil'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Mexico', 'Mexico'), ('Peru', 'Peru'), ('Russia', 'Russia'), ('United States', 'United States'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('France', 'France'), ('Denmark', 'Denmark'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Belgium', 'Belgium'), ('Netherlands', 'Netherlands'), ('Portugal', 'Portugal'), ('Iceland', 'Iceland'), ('Philippines', 'Philippines'), ('Vietnam', 'Vietnam'), ('United Arab Emirates', 'United Arab Emirates'), ('Saudi Arabia', 'Saudi Arabia'), ('Canada', 'Canada')], max_length=30, unique=True),
        ),
    ]
